export type { EmailAccount, CreateEmailAccountInput, EmailMonitorDeps } from './types.js'
export type { ParsedMail } from 'mailparser'
export type { Driver } from 'unstorage'
export { createEmailMonitor } from './monitor.js'
export type { Storage } from 'unstorage'
